services:
  - type: web
    name: laravel-login-page
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      php artisan migrate --force
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://laravite-myloginpage.onrender.com
      - key: APP_KEY
        value: base64:Ucq8ytE+DtjKwLb9vrj0tNA6QKRsQP+u3Z1ncaoWgpo=
      - key: FORCE_HTTPS
        value: true
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_LIFETIME
        value: 120
      - key: SESSION_SECURE_COOKIE
        value: true
      - key: SESSION_HTTP_ONLY
        value: true
      - key: SESSION_SAME_SITE
        value: lax
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /opt/render/project/src/database/database.sqlite
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        value: your-email@gmail.com
      - key: MAIL_PASSWORD
        value: your-app-password
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        value: your-email@gmail.com
      - key: MAIL_FROM_NAME
        value: "Laravel Login Page"